const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.HTMLElement,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Cnds.OnTweensPingPong,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.HTMLElement.Acts.SetPos,
		C3.Plugins.HTMLElement.Exps.LayerName,
		C3.Plugins.HTMLElement.Cnds.OnClickedClass,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.JavaScriptInEvents.Game_Event55_Act1,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.HTMLElement.Acts.Destroy,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.JavaScriptInEvents.Backend_Event2_Act1,
		C3.JavaScriptInEvents.Backend_Event3_Act1,
		C3.JavaScriptInEvents.Backend_Event4_Act2,
		C3.JavaScriptInEvents.Backend_Event5_Act2,
		C3.Plugins.System.Cnds.IsPreview,
		C3.JavaScriptInEvents.Backend_Event6_Act1,
		C3.JavaScriptInEvents.Backend_Event7_Act1,
		C3.JavaScriptInEvents.Backend_Event8_Act1,
		C3.JavaScriptInEvents.Backend_Event9_Act1,
		C3.JavaScriptInEvents.Backend_Event10_Act1,
		C3.JavaScriptInEvents.Backend_Event11_Act1,
		C3.JavaScriptInEvents.Backend_Event12_Act1,
		C3.JavaScriptInEvents.Backend_Event13_Act1,
		C3.JavaScriptInEvents.Backend_Event14_Act1,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.JavaScriptInEvents.Playfab_Event1_Act1,
		C3.JavaScriptInEvents.Playfab_Event3_Act1,
		C3.JavaScriptInEvents.Playfab_Event4_Act1,
		C3.JavaScriptInEvents.Playfab_Event5_Act1,
		C3.JavaScriptInEvents.Playfab_Event6_Act1,
		C3.Plugins.HTMLElement.Acts.SetX,
		C3.JavaScriptInEvents.Playfab_Event8_Act1
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{AdvancedRandom: 0},
	{dict_cookies: 0},
	{Browser: 0},
	{html_cta: 0},
	{html_leaderboard: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{name: 0},
	{colorTypeName: 0},
	{Sine: 0},
	{Tween: 0},
	{btn_9patch: 0},
	{frameChosen: 0},
	{xx: 0},
	{yy: 0},
	{state: 0},
	{Fade: 0},
	{card: 0},
	{endImage: 0},
	{hand: 0},
	{imgCard: 0},
	{logo: 0},
	{playablyLogo: 0},
	{txt_button: 0},
	{iconString: 0},
	{txt_header: 0},
	{txt_roundEnd_sub: 0},
	{locations: 0},
	{Sprite: 0},
	{icons: 0},
	{Rotate: 0},
	{loading: 0},
	{famTexts: 0},
	{famCards: 0},
	{rows: 0},
	{cols: 0},
	{lvl: 0},
	{isPlaying: 0},
	{totalCards: 0},
	{scoreSeconds: 0},
	{gameState: 0},
	{canTap: 0},
	{adjustedValue: 0},
	{ww: 0},
	{spacingX: 0},
	{spacingY: 0},
	{startX: 0},
	{startY: 0},
	{debug: 0},
	{cc: 0},
	{uniqueMatching: 0},
	{frameCount: 0},
	{lyr: 0},
	{html_email: 0},
	{playfab_id: 0},
	{html_name: 0},
	{Status: 0},
	{gameResult: 0},
	{scoreToSend: 0},
	{dataName: 0},
	{dataValue: 0},
	{showLayer: 0},
	{playfab_titleID: 0},
	{playfab_isDebug: 0},
	{newName: 0},
	{newEmail: 0},
	{statisticName: 0},
	{leaderboardName: 0},
	{maxInList: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	dict_cookies: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	html_cta: class extends self.IHTMLElementInstance {},
	html_leaderboard: class extends self.IHTMLElementInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	btn_9patch: class extends self.I9PatchInstance {},
	card: class extends self.ISpriteInstance {},
	endImage: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	imgCard: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	playablyLogo: class extends self.ISpriteInstance {},
	txt_button: class extends self.ITextInstance {},
	txt_header: class extends self.ITextInstance {},
	txt_roundEnd_sub: class extends self.ITextInstance {},
	locations: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	icons: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	famTexts: class extends self.ITextInstance {},
	famCards: class extends self.ISpriteInstance {}
}